from typing import Annotated, List
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    assets_under_analysis: Annotated[
        List[str], "All crypto assets handled in the current run"
    ]
    trade_date: Annotated[str, "What date we are trading at"]
    available_capital: Annotated[float, "User-provided capital for this trading session"]
    min_leverage: Annotated[
        int, "Minimum leverage allowed for this trading session (integer only)"
    ]
    max_leverage: Annotated[
        int, "Maximum leverage allowed for this trading session (integer only)"
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Crypto Market Analyst"]
    newsflash_report: Annotated[str, "Report from the Odaily newsflash analyst"]
    longform_report: Annotated[str, "Report from the Odaily longform analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    trader_investment_plan: Annotated[str, "Unified plan generated by the Trader"]

    # execution step
    final_trade_decision: Annotated[str, "Final execution result after risk control"]

    interaction_round: Annotated[int, "Current reasoning round shared by all agents"]

    # 仓位信息
    current_positions: Annotated[str, "Current Binance futures positions fetched by Trader"]
