from typing import Annotated, Sequence, Dict, List
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management stage state
class RiskReviewState(TypedDict):
    history: Annotated[str, "Chronological risk notes across sessions"]
    analyst_report: Annotated[str, "Latest structured report from the risk manager"]
    manager_summary: Annotated[str, "Latest summary/decision from the general manager"]
    count: Annotated[int, "How many times the risk manager has reviewed this trade"]


class AgentState(MessagesState):
    assets_under_analysis: Annotated[
        List[str], "All crypto assets handled in the current run"
    ]
    trade_date: Annotated[str, "What date we are trading at"]
    available_capital: Annotated[
        float, "User-provided capital that Trader/Risk/Manager can allocate"
    ]
    min_leverage: Annotated[
        float, "Minimum leverage allowed for this trading session"
    ]
    max_leverage: Annotated[
        float, "Maximum leverage allowed for this trading session"
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Crypto Market Analyst"]
    newsflash_report: Annotated[str, "Report from the Odaily newsflash analyst"]
    longform_report: Annotated[str, "Report from the Odaily longform analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    trader_investment_plan: Annotated[str, "Unified plan generated by the Trader"]

    # risk management + manager step
    risk_review_state: Annotated[
        RiskReviewState, "Current state of the risk manager review"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Manager"]

    interaction_round: Annotated[int, "Current reasoning round shared by all agents"]
